my stupidity fixes

diff --git a/system/bin/fmount b/system/bin/fmount
--- a/system/bin/fmount
+++ b/system/bin/fmount
@@ -68,14 +68,13 @@ EOM
         if ! mountpoint -q "/mnt/runtime/default/emulated/0/$src"
         then
             echo "Mounting $dest -> /data/media/0/$src..." >> $LOG
-            mount -o bind "$dest" "/data/media/0/$src" 1>>$LOG 2>>$LOG # old style mounting
-            # if ! mount -o bind "$dest" "/data/media/0/$src" 1>>$LOG 2>>$LOG
-            # then
-            #     echo "Failed. Mounting $dest -> /mnt/runtime/default/emulated/0/$src..." >> $LOG
-            #     mount -o bind "$dest" "/mnt/runtime/default/emulated/0/$src" 1>>$LOG 2>>$LOG
-            #     mount -o bind "$dest" "/mnt/runtime/read/emulated/0/$src" 1>>$LOG 2>>$LOG
-            #     mount -o bind "$dest" "/mnt/runtime/write/emulated/0/$src" 1>>$LOG 2>>$LOG
-            # fi
+            if ! mount -o bind "$dest" "/data/media/0/$src" 1>>$LOG 2>>$LOG
+            then
+                echo "Failed. Mounting $dest -> /mnt/runtime/default/emulated/0/$src..." >> $LOG
+                mount -o bind "$dest" "/mnt/runtime/default/emulated/0/$src" 1>>$LOG 2>>$LOG
+                mount -o bind "$dest" "/mnt/runtime/read/emulated/0/$src" 1>>$LOG 2>>$LOG
+                mount -o bind "$dest" "/mnt/runtime/write/emulated/0/$src" 1>>$LOG 2>>$LOG
+            fi
             echo "Done!" >> $LOG
             if [[ ! -f $BINDLIST ]];
             then
@@ -136,12 +135,13 @@ function debugFunc() {
 function listFunc() {
 	if [[ -f $BINDLIST ]]; then
 		while IFS='' read -r line || [[ -n "$line" ]]; do
+			dest=`echo "$line" | awk '{print $1;}'`
 			src=`echo "$line" | awk '{print $2;}'`
 			if mountpoint -q "/data/media/0/$src"
 			then
-				echo "$line	MOUNTED"
+				echo "$dest $DATAPATH/$src	MOUNTED"
 			else
-				echo "$line	NOT MOUNTED"
+				echo "$dest $DATAPATH/$src	NOT MOUNTED"
 			fi 
 		done < "$BINDLIST"
 		exit 0
@@ -157,22 +157,22 @@ function listFunc() {
 function rebindFunc() {
 	if [[ -f $BINDLIST ]]; then
 		while IFS='' read -r line || [[ -n "$line" ]]; do
-			$dest=`echo "$line" | awk '{print $1;}'`
-			$src=`echo "$line" | awk '{print $2;}'`
+			dest=`echo "$line" | awk '{print $1;}'`
+			src=`echo "$line" | awk '{print $2;}'`
 			
 			if ! mountpoint -q "/data/media/0/$src"
     		then
         		if ! mountpoint -q "/mnt/runtime/default/emulated/0/$src"
         		then
             		echo "Mounting $dest -> /data/media/0/$src..." >> $LOG
-            		mount -o bind "$dest" "/data/media/0/$src" 1>>$LOG 2>>$LOG # old style mounting
-            		# if ! mount -o bind "$dest" "/data/media/0/$src" 1>>$LOG 2>>$LOG
-            		# then
-                	# 	echo "Failed. Mounting $dest -> /mnt/runtime/default/emulated/0/$src..." >> $LOG
-                	# 	mount -o bind "$dest" "/mnt/runtime/default/emulated/0/$src" 1>>$LOG 2>>$LOG
-                	# 	mount -o bind "$dest" "/mnt/runtime/read/emulated/0/$src" 1>>$LOG 2>>$LOG
-                	# 	mount -o bind "$dest" "/mnt/runtime/write/emulated/0/$src" 1>>$LOG 2>>$LOG
-           			# fi
+            		
+            		if ! mount -o bind "$dest" "/data/media/0/$src" 1>>$LOG 2>>$LOG
+            		then
+                		echo "Failed. Mounting $dest -> /mnt/runtime/default/emulated/0/$src..." >> $LOG
+                		mount -o bind "$dest" "/mnt/runtime/default/emulated/0/$src" 1>>$LOG 2>>$LOG
+                		mount -o bind "$dest" "/mnt/runtime/read/emulated/0/$src" 1>>$LOG 2>>$LOG
+                		mount -o bind "$dest" "/mnt/runtime/write/emulated/0/$src" 1>>$LOG 2>>$LOG
+           			fi
             		echo "Done!" >> $LOG
             	
         		else
@@ -196,7 +196,7 @@ function rebindFunc() {
 
 function helpFunc() {
 	cat << EOM
-Magisk FolderMount v0.8.9-b2
+Magisk FolderMount v0.8.9-b4
 
 Internal SD card: $DATAPATH
 External SD card: $EXTSDPATH
